[pytest]
addopts = -v --tb=short --screenshot=only-on-failure --video=retain-on-failure

testpaths = tests
pythonpath = .

markers =
	login: login scenarios
	cart: add-to-cart scenarios
	checkout: checkout and confirmation scenarios
	checkout_validation: checkout form validation scenarios

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S
