name: Run Swag Labs Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium
        run: python -m playwright install --with-deps chromium

      - name: Run login tests
        run: python -m pytest tests/test_login.py -v

      - name: Run add to cart test
        run: python -m pytest tests/test_add_to_cart.py -v

      - name: Run checkout test
        run: python -m pytest tests/test_checkout.py -v

      - name: Run checkout validation tests
        run: python -m pytest tests/test_checkout_negative.py -v